In [1]:
import tensorflow as tf
import numpy as np


In [2]:
X_train = (np.random.sample((10000,5)))
y_train = np.random.sample((10000,1))

In [5]:
print(X_train)
#print(y_train)

[[0.62962084 0.42173306 0.14603876 0.35251725 0.63342789]
 [0.91308952 0.83444338 0.33650761 0.54214753 0.85159393]
 [0.14087759 0.97181189 0.33823503 0.7991944  0.12834076]
 ...
 [0.86303424 0.9464491  0.31237761 0.95898334 0.22750524]
 [0.55228259 0.32967689 0.62254341 0.33432209 0.11224892]
 [0.42904517 0.37535567 0.0933068  0.68878843 0.14503974]]


In [6]:
X_train.shape

(10000, 5)

In [7]:
feature_columns = [
    tf.feature_column.numeric_column('x', shape=X_train.shape[1:])]
DNN_reg = tf.estimator.DNNRegressor(feature_columns=feature_columns,model_dir='train/linreg',hidden_units=[500,300], optimizer=tf.train.ProximalAdagradOptimizer(
        learning_rate=0.1,
        l1_regularization_strength=0.001
    )                                   )


In [9]:
train_input = tf.estimator.inputs.numpy_input_fn(
    x={"x": X_train},
    y=y_train,
    shuffle=False, num_epochs=None
)

DNN_reg.train(train_input, steps=3000)

W0213 15:35:24.505742  5792 deprecation.py:323] From C:\installs\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0213 15:35:24.518790  5792 deprecation.py:323] From C:\installs\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0213 15:35:24.520716  5792 deprecation.py:323] From C:\installs\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_functions.py:500