In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images,test_labels) = mnist.load_data()

In [3]:
train_images.shape
len(train_labels)
#@!$%train_labels

print(train_images.shape)

(60000, 28, 28)


In [4]:
test_images.shape
len(test_labels)
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [5]:
digit = train_images[4]

In [6]:
import matplotlib.pyplot as plt
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

In [7]:
my_slice = train_images[10: 100]

# equivalent to train_images[10:100, 0:28, 0:28]

In [23]:
print(my_slice)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [8]:
print(train_images[:, 14:, 14:])

[[[240 253 253 ...   0   0   0]
  [ 45 186 253 ...   0   0   0]
  [  0  16  93 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[241 243 234 ...   0   0   0]
  [143  91  28 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[253 254 253 ...   0   0   0]
  [ 72 192 254 ...   0   0   0]
  [  0   6 242 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0  31 127 ...   0   0   0]
  [ 27 218 252 ...   0   0   0]
  [194 253 217 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0  

In [9]:
print(train_images[:, 7:-7, 7:-7])


[[[ 49 238 253 ...  93  82  82]
  [ 18 219 253 ...   0   0   0]
  [  0  80 156 ...   0   0   0]
  ...
  [  0   0   0 ... 253 207   2]
  [  0   0   0 ... 250 182   0]
  [  0   0   0 ...  78   0   0]]

 [[  0   0   0 ...  84 252 253]
  [  0   0   0 ...  96 189 253]
  [  0   0   0 ...  47  79 255]
  ...
  [252 145   0 ... 252 173   0]
  [253 225   0 ... 162   0   0]
  [252 249 146 ...  56   0   0]]

 [[  0   0   0 ...   0   2 153]
  [  0   0   0 ...   0  27 254]
  [  0   0   0 ...   0 183 254]
  ...
  [  0   0   0 ... 254  57   0]
  [  0   0   0 ... 254  57   0]
  [  0   0   0 ... 255  94   0]]

 ...

 [[  0   0   0 ... 223 159 131]
  [  0   0   0 ...  27   0   0]
  [  0   0  54 ...   0   0   0]
  ...
  [  0   0   0 ... 173   0   0]
  [  0   0   0 ... 173   0   0]
  [  0   0   0 ...  74   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [247 110   0 ... 146 163  63]
  [236 128   0 ... 178  12   0]
  [239 196 169 ...   0   0  

In [10]:
batch =train_images[:128]

print(batch)

# first axis is the batch axis or tensor
# e first axis is the samples axis and the second axis is the features axis.

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


real world example of data tensors

Vector data—2D tensors of shape (samples, features)
 Timeseries data or sequence data—3D tensors of shape (samples, timesteps,
features)
 Images—4D tensors of shape (samples, height, width, channels) or (samples,
channels, height, width)
 Video—5D tensors of shape (samples, frames, height, width, channels) or
(samples, frames, channels, height, width)

In [6]:
from keras import models
from keras import layers

In [7]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))

In [12]:
 #Dense here indicates fillu connected layers

In [8]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics= ['accuracy'])

In [9]:
print(train_images.shape)

(60000, 28, 28)


In [10]:
train_images = train_images.reshape((60000, 28*28))

In [11]:
print(train_images.shape)

(60000, 784)


TypeError: Invalid shape (784,) for image data

In [17]:
train_images = train_images.astype('float32') /255

In [18]:
test_images = test_images.reshape(10000,28 *28)

In [19]:
test_images = test_images.astype('float32')/255

In [20]:
from keras.utils import to_categorical

In [21]:
print(train_labels)

[5 0 4 ... 5 6 8]


In [22]:
train_labels = to_categorical(train_labels)

In [24]:
test_labels = to_categorical(test_labels)

In [25]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

W1006 06:42:27.773000  9388 deprecation_wrapper.py:119] From C:\installs\Anaconda\envs\tf_gpu\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.



Epoch 1/5
60000/60000 [==============================] - 6s 100us/step - loss: 0.2504 - accuracy: 0.9284
Epoch 2/5
60000/60000 [==============================] - 4s 65us/step - loss: 0.1029 - accuracy: 0.9694
Epoch 3/5
60000/60000 [==============================] - 4s 65us/step - loss: 0.0678 - accuracy: 0.9798
Epoch 4/5
60000/60000 [==============================] - 4s 66us/step - loss: 0.0486 - accuracy: 0.9854
Epoch 5/5
60000/60000 [==============================] - 4s 71us/step - loss: 0.0373 - accuracy: 0.9891


In [26]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print("test_loss : ", test_loss)
print("test_ acc : ", test_acc)

10000/10000 [==============================] - 2s 158us/step
test_loss :  0.06569429872743786
test_ acc :  0.9789999723434448
