In [1]:
from keras.layers import Embedding
embedding_layer = Embedding(1000,64)

from keras.datasets import imdb
from keras import preprocessing


Using TensorFlow backend.


In [2]:
import os
imdb_dir = './imdb'
train_dir = os.path.join(imdb_dir, 'train')

In [3]:
print(train_dir)

./imdb\train


In [4]:
labels = []
texts = []

# I had to manually assign encoding = "utf8" for it to work

for label_type in ['neg', 'pos']:
    dir_name = os.path.join(train_dir, label_type)
    for fname in os.listdir(dir_name):
        if fname[-4:] == '.txt':
            f = open(os.path.join(dir_name, fname),encoding="utf8")
            texts.append(f.read())
            f.close()
            if label_type == 'neg':
                labels.append(0)
            else:
                labels.append(1)

In [5]:
#tokenizing the data

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

maxlen = 100
training_samples = 200
validation_samples = 10000
max_words = 10000

tokenizer = Tokenizer(num_words = max_words)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
print('Found %s unique tokens'% len(word_index))

data = pad_sequences(sequences, maxlen=maxlen)


Found 88582 unique tokens


In [6]:
print(data[0])

[  34   44 7576 1414   15    3 4252  514   43   16    3  633  133   12
    6    3 1301  459    4 1751  209    3 7693  308    6  676   80   32
 2137 1110 3008   31    1  929    4   42 5120  469    9 2665 1751    1
  223   55   16   54  828 1318  847  228    9   40   96  122 1484   57
  145   36    1  996  141   27  676  122    1  411   59   94 2278  303
  772    5    3  837   20    3 1755  646   42  125   71   22  235  101
   16   46   49  624   31  702   84  702  378 3493    2 8422   67   27
  107 3348]


In [7]:
labels = np.asarray(labels)
print('Shape of data tensor: ', data.shape)
print('Shape of label tensor: ', labels.shape)

indices = np.arange(data.shape[0])
print(indices)
np.random.shuffle(indices)
print(indices)

data = data[indices]
labels = labels[indices]

print(data)
print(labels)
x_train = data[:training_samples]
y_train = labels[:training_samples]
x_val = data[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]

Shape of data tensor:  (25000, 100)
Shape of label tensor:  (25000,)
[    0     1     2 ... 24997 24998 24999]
[ 3060  8589 15711 ... 11550 21761 19613]
[[  14    3 2324 ... 2324  339  155]
 [ 225    6   50 ...   95   25  250]
 [9090    2    1 ...    3  159 1537]
 ...
 [  11   43   85 ...    6    5   27]
 [  18  123    1 ...   55    5  213]
 [5499 5960   31 ...  447 9398    2]]
[0 0 1 ... 0 1 1]


In [ ]:
glove_
